package leo.wan.model;

import java.util.ArrayList;
import java.util.List;

public class CostProjectDetailExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    public CostProjectDetailExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andLevel1NameIsNull() {
            addCriterion("level_1_name is null");
            return (Criteria) this;
        }

        public Criteria andLevel1NameIsNotNull() {
            addCriterion("level_1_name is not null");
            return (Criteria) this;
        }

        public Criteria andLevel1NameEqualTo(String value) {
            addCriterion("level_1_name =", value, "level1Name");
            return (Criteria) this;
        }

        public Criteria andLevel1NameNotEqualTo(String value) {
            addCriterion("level_1_name <>", value, "level1Name");
            return (Criteria) this;
        }

        public Criteria andLevel1NameGreaterThan(String value) {
            addCriterion("level_1_name >", value, "level1Name");
            return (Criteria) this;
        }

        public Criteria andLevel1NameGreaterThanOrEqualTo(String value) {
            addCriterion("level_1_name >=", value, "level1Name");
            return (Criteria) this;
        }

        public Criteria andLevel1NameLessThan(String value) {
            addCriterion("level_1_name <", value, "level1Name");
            return (Criteria) this;
        }

        public Criteria andLevel1NameLessThanOrEqualTo(String value) {
            addCriterion("level_1_name <=", value, "level1Name");
            return (Criteria) this;
        }

        public Criteria andLevel1NameLike(String value) {
            addCriterion("level_1_name like", value, "level1Name");
            return (Criteria) this;
        }

        public Criteria andLevel1NameNotLike(String value) {
            addCriterion("level_1_name not like", value, "level1Name");
            return (Criteria) this;
        }

        public Criteria andLevel1NameIn(List<String> values) {
            addCriterion("level_1_name in", values, "level1Name");
            return (Criteria) this;
        }

        public Criteria andLevel1NameNotIn(List<String> values) {
            addCriterion("level_1_name not in", values, "level1Name");
            return (Criteria) this;
        }

        public Criteria andLevel1NameBetween(String value1, String value2) {
            addCriterion("level_1_name between", value1, value2, "level1Name");
            return (Criteria) this;
        }

        public Criteria andLevel1NameNotBetween(String value1, String value2) {
            addCriterion("level_1_name not between", value1, value2, "level1Name");
            return (Criteria) this;
        }

        public Criteria andLevel2NameIsNull() {
            addCriterion("level_2_name is null");
            return (Criteria) this;
        }

        public Criteria andLevel2NameIsNotNull() {
            addCriterion("level_2_name is not null");
            return (Criteria) this;
        }

        public Criteria andLevel2NameEqualTo(String value) {
            addCriterion("level_2_name =", value, "level2Name");
            return (Criteria) this;
        }

        public Criteria andLevel2NameNotEqualTo(String value) {
            addCriterion("level_2_name <>", value, "level2Name");
            return (Criteria) this;
        }

        public Criteria andLevel2NameGreaterThan(String value) {
            addCriterion("level_2_name >", value, "level2Name");
            return (Criteria) this;
        }

        public Criteria andLevel2NameGreaterThanOrEqualTo(String value) {
            addCriterion("level_2_name >=", value, "level2Name");
            return (Criteria) this;
        }

        public Criteria andLevel2NameLessThan(String value) {
            addCriterion("level_2_name <", value, "level2Name");
            return (Criteria) this;
        }

        public Criteria andLevel2NameLessThanOrEqualTo(String value) {
            addCriterion("level_2_name <=", value, "level2Name");
            return (Criteria) this;
        }

        public Criteria andLevel2NameLike(String value) {
            addCriterion("level_2_name like", value, "level2Name");
            return (Criteria) this;
        }

        public Criteria andLevel2NameNotLike(String value) {
            addCriterion("level_2_name not like", value, "level2Name");
            return (Criteria) this;
        }

        public Criteria andLevel2NameIn(List<String> values) {
            addCriterion("level_2_name in", values, "level2Name");
            return (Criteria) this;
        }

        public Criteria andLevel2NameNotIn(List<String> values) {
            addCriterion("level_2_name not in", values, "level2Name");
            return (Criteria) this;
        }

        public Criteria andLevel2NameBetween(String value1, String value2) {
            addCriterion("level_2_name between", value1, value2, "level2Name");
            return (Criteria) this;
        }

        public Criteria andLevel2NameNotBetween(String value1, String value2) {
            addCriterion("level_2_name not between", value1, value2, "level2Name");
            return (Criteria) this;
        }

        public Criteria andLevel3NameIsNull() {
            addCriterion("level_3_name is null");
            return (Criteria) this;
        }

        public Criteria andLevel3NameIsNotNull() {
            addCriterion("level_3_name is not null");
            return (Criteria) this;
        }

        public Criteria andLevel3NameEqualTo(String value) {
            addCriterion("level_3_name =", value, "level3Name");
            return (Criteria) this;
        }

        public Criteria andLevel3NameNotEqualTo(String value) {
            addCriterion("level_3_name <>", value, "level3Name");
            return (Criteria) this;
        }

        public Criteria andLevel3NameGreaterThan(String value) {
            addCriterion("level_3_name >", value, "level3Name");
            return (Criteria) this;
        }

        public Criteria andLevel3NameGreaterThanOrEqualTo(String value) {
            addCriterion("level_3_name >=", value, "level3Name");
            return (Criteria) this;
        }

        public Criteria andLevel3NameLessThan(String value) {
            addCriterion("level_3_name <", value, "level3Name");
            return (Criteria) this;
        }

        public Criteria andLevel3NameLessThanOrEqualTo(String value) {
            addCriterion("level_3_name <=", value, "level3Name");
            return (Criteria) this;
        }

        public Criteria andLevel3NameLike(String value) {
            addCriterion("level_3_name like", value, "level3Name");
            return (Criteria) this;
        }

        public Criteria andLevel3NameNotLike(String value) {
            addCriterion("level_3_name not like", value, "level3Name");
            return (Criteria) this;
        }

        public Criteria andLevel3NameIn(List<String> values) {
            addCriterion("level_3_name in", values, "level3Name");
            return (Criteria) this;
        }

        public Criteria andLevel3NameNotIn(List<String> values) {
            addCriterion("level_3_name not in", values, "level3Name");
            return (Criteria) this;
        }

        public Criteria andLevel3NameBetween(String value1, String value2) {
            addCriterion("level_3_name between", value1, value2, "level3Name");
            return (Criteria) this;
        }

        public Criteria andLevel3NameNotBetween(String value1, String value2) {
            addCriterion("level_3_name not between", value1, value2, "level3Name");
            return (Criteria) this;
        }

        public Criteria andUnitIsNull() {
            addCriterion("unit is null");
            return (Criteria) this;
        }

        public Criteria andUnitIsNotNull() {
            addCriterion("unit is not null");
            return (Criteria) this;
        }

        public Criteria andUnitEqualTo(String value) {
            addCriterion("unit =", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotEqualTo(String value) {
            addCriterion("unit <>", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThan(String value) {
            addCriterion("unit >", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitGreaterThanOrEqualTo(String value) {
            addCriterion("unit >=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThan(String value) {
            addCriterion("unit <", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLessThanOrEqualTo(String value) {
            addCriterion("unit <=", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitLike(String value) {
            addCriterion("unit like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotLike(String value) {
            addCriterion("unit not like", value, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitIn(List<String> values) {
            addCriterion("unit in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotIn(List<String> values) {
            addCriterion("unit not in", values, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitBetween(String value1, String value2) {
            addCriterion("unit between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andUnitNotBetween(String value1, String value2) {
            addCriterion("unit not between", value1, value2, "unit");
            return (Criteria) this;
        }

        public Criteria andSupplyUnitCostIsNull() {
            addCriterion("supply_unit_cost is null");
            return (Criteria) this;
        }

        public Criteria andSupplyUnitCostIsNotNull() {
            addCriterion("supply_unit_cost is not null");
            return (Criteria) this;
        }

        public Criteria andSupplyUnitCostEqualTo(Long value) {
            addCriterion("supply_unit_cost =", value, "supplyUnitCost");
            return (Criteria) this;
        }

        public Criteria andSupplyUnitCostNotEqualTo(Long value) {
            addCriterion("supply_unit_cost <>", value, "supplyUnitCost");
            return (Criteria) this;
        }

        public Criteria andSupplyUnitCostGreaterThan(Long value) {
            addCriterion("supply_unit_cost >", value, "supplyUnitCost");
            return (Criteria) this;
        }

        public Criteria andSupplyUnitCostGreaterThanOrEqualTo(Long value) {
            addCriterion("supply_unit_cost >=", value, "supplyUnitCost");
            return (Criteria) this;
        }

        public Criteria andSupplyUnitCostLessThan(Long value) {
            addCriterion("supply_unit_cost <", value, "supplyUnitCost");
            return (Criteria) this;
        }

        public Criteria andSupplyUnitCostLessThanOrEqualTo(Long value) {
            addCriterion("supply_unit_cost <=", value, "supplyUnitCost");
            return (Criteria) this;
        }

        public Criteria andSupplyUnitCostIn(List<Long> values) {
            addCriterion("supply_unit_cost in", values, "supplyUnitCost");
            return (Criteria) this;
        }

        public Criteria andSupplyUnitCostNotIn(List<Long> values) {
            addCriterion("supply_unit_cost not in", values, "supplyUnitCost");
            return (Criteria) this;
        }

        public Criteria andSupplyUnitCostBetween(Long value1, Long value2) {
            addCriterion("supply_unit_cost between", value1, value2, "supplyUnitCost");
            return (Criteria) this;
        }

        public Criteria andSupplyUnitCostNotBetween(Long value1, Long value2) {
            addCriterion("supply_unit_cost not between", value1, value2, "supplyUnitCost");
            return (Criteria) this;
        }

        public Criteria andInstallUnitCostIsNull() {
            addCriterion("install_unit_cost is null");
            return (Criteria) this;
        }

        public Criteria andInstallUnitCostIsNotNull() {
            addCriterion("install_unit_cost is not null");
            return (Criteria) this;
        }

        public Criteria andInstallUnitCostEqualTo(Long value) {
            addCriterion("install_unit_cost =", value, "installUnitCost");
            return (Criteria) this;
        }

        public Criteria andInstallUnitCostNotEqualTo(Long value) {
            addCriterion("install_unit_cost <>", value, "installUnitCost");
            return (Criteria) this;
        }

        public Criteria andInstallUnitCostGreaterThan(Long value) {
            addCriterion("install_unit_cost >", value, "installUnitCost");
            return (Criteria) this;
        }

        public Criteria andInstallUnitCostGreaterThanOrEqualTo(Long value) {
            addCriterion("install_unit_cost >=", value, "installUnitCost");
            return (Criteria) this;
        }

        public Criteria andInstallUnitCostLessThan(Long value) {
            addCriterion("install_unit_cost <", value, "installUnitCost");
            return (Criteria) this;
        }

        public Criteria andInstallUnitCostLessThanOrEqualTo(Long value) {
            addCriterion("install_unit_cost <=", value, "installUnitCost");
            return (Criteria) this;
        }

        public Criteria andInstallUnitCostIn(List<Long> values) {
            addCriterion("install_unit_cost in", values, "installUnitCost");
            return (Criteria) this;
        }

        public Criteria andInstallUnitCostNotIn(List<Long> values) {
            addCriterion("install_unit_cost not in", values, "installUnitCost");
            return (Criteria) this;
        }

        public Criteria andInstallUnitCostBetween(Long value1, Long value2) {
            addCriterion("install_unit_cost between", value1, value2, "installUnitCost");
            return (Criteria) this;
        }

        public Criteria andInstallUnitCostNotBetween(Long value1, Long value2) {
            addCriterion("install_unit_cost not between", value1, value2, "installUnitCost");
            return (Criteria) this;
        }

        public Criteria andCostProjectIdIsNull() {
            addCriterion("cost_project_id is null");
            return (Criteria) this;
        }

        public Criteria andCostProjectIdIsNotNull() {
            addCriterion("cost_project_id is not null");
            return (Criteria) this;
        }

        public Criteria andCostProjectIdEqualTo(Integer value) {
            addCriterion("cost_project_id =", value, "costProjectId");
            return (Criteria) this;
        }

        public Criteria andCostProjectIdNotEqualTo(Integer value) {
            addCriterion("cost_project_id <>", value, "costProjectId");
            return (Criteria) this;
        }

        public Criteria andCostProjectIdGreaterThan(Integer value) {
            addCriterion("cost_project_id >", value, "costProjectId");
            return (Criteria) this;
        }

        public Criteria andCostProjectIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("cost_project_id >=", value, "costProjectId");
            return (Criteria) this;
        }

        public Criteria andCostProjectIdLessThan(Integer value) {
            addCriterion("cost_project_id <", value, "costProjectId");
            return (Criteria) this;
        }

        public Criteria andCostProjectIdLessThanOrEqualTo(Integer value) {
            addCriterion("cost_project_id <=", value, "costProjectId");
            return (Criteria) this;
        }

        public Criteria andCostProjectIdIn(List<Integer> values) {
            addCriterion("cost_project_id in", values, "costProjectId");
            return (Criteria) this;
        }

        public Criteria andCostProjectIdNotIn(List<Integer> values) {
            addCriterion("cost_project_id not in", values, "costProjectId");
            return (Criteria) this;
        }

        public Criteria andCostProjectIdBetween(Integer value1, Integer value2) {
            addCriterion("cost_project_id between", value1, value2, "costProjectId");
            return (Criteria) this;
        }

        public Criteria andCostProjectIdNotBetween(Integer value1, Integer value2) {
            addCriterion("cost_project_id not between", value1, value2, "costProjectId");
            return (Criteria) this;
        }

        public Criteria andLevel4NameIsNull() {
            addCriterion("level_4_name is null");
            return (Criteria) this;
        }

        public Criteria andLevel4NameIsNotNull() {
            addCriterion("level_4_name is not null");
            return (Criteria) this;
        }

        public Criteria andLevel4NameEqualTo(String value) {
            addCriterion("level_4_name =", value, "level4Name");
            return (Criteria) this;
        }

        public Criteria andLevel4NameNotEqualTo(String value) {
            addCriterion("level_4_name <>", value, "level4Name");
            return (Criteria) this;
        }

        public Criteria andLevel4NameGreaterThan(String value) {
            addCriterion("level_4_name >", value, "level4Name");
            return (Criteria) this;
        }

        public Criteria andLevel4NameGreaterThanOrEqualTo(String value) {
            addCriterion("level_4_name >=", value, "level4Name");
            return (Criteria) this;
        }

        public Criteria andLevel4NameLessThan(String value) {
            addCriterion("level_4_name <", value, "level4Name");
            return (Criteria) this;
        }

        public Criteria andLevel4NameLessThanOrEqualTo(String value) {
            addCriterion("level_4_name <=", value, "level4Name");
            return (Criteria) this;
        }

        public Criteria andLevel4NameLike(String value) {
            addCriterion("level_4_name like", value, "level4Name");
            return (Criteria) this;
        }

        public Criteria andLevel4NameNotLike(String value) {
            addCriterion("level_4_name not like", value, "level4Name");
            return (Criteria) this;
        }

        public Criteria andLevel4NameIn(List<String> values) {
            addCriterion("level_4_name in", values, "level4Name");
            return (Criteria) this;
        }

        public Criteria andLevel4NameNotIn(List<String> values) {
            addCriterion("level_4_name not in", values, "level4Name");
            return (Criteria) this;
        }

        public Criteria andLevel4NameBetween(String value1, String value2) {
            addCriterion("level_4_name between", value1, value2, "level4Name");
            return (Criteria) this;
        }

        public Criteria andLevel4NameNotBetween(String value1, String value2) {
            addCriterion("level_4_name not between", value1, value2, "level4Name");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cost_project_detail
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}