package leo.wan.model;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table cost_project_detail
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class CostProjectDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_project_detail.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_project_detail.level_1_name
     *
     * @mbggenerated
     */
    private String level1Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_project_detail.level_2_name
     *
     * @mbggenerated
     */
    private String level2Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_project_detail.level_3_name
     *
     * @mbggenerated
     */
    private String level3Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_project_detail.unit
     *
     * @mbggenerated
     */
    private String unit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_project_detail.supply_unit_cost
     *
     * @mbggenerated
     */
    private Long supplyUnitCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_project_detail.install_unit_cost
     *
     * @mbggenerated
     */
    private Long installUnitCost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_project_detail.cost_project_id
     *
     * @mbggenerated
     */
    private Integer costProjectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cost_project_detail.level_4_name
     *
     * @mbggenerated
     */
    private String level4Name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_project_detail.id
     *
     * @return the value of cost_project_detail.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_project_detail.id
     *
     * @param id the value for cost_project_detail.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_project_detail.level_1_name
     *
     * @return the value of cost_project_detail.level_1_name
     *
     * @mbggenerated
     */
    public String getLevel1Name() {
        return level1Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_project_detail.level_1_name
     *
     * @param level1Name the value for cost_project_detail.level_1_name
     *
     * @mbggenerated
     */
    public void setLevel1Name(String level1Name) {
        this.level1Name = level1Name == null ? null : level1Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_project_detail.level_2_name
     *
     * @return the value of cost_project_detail.level_2_name
     *
     * @mbggenerated
     */
    public String getLevel2Name() {
        return level2Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_project_detail.level_2_name
     *
     * @param level2Name the value for cost_project_detail.level_2_name
     *
     * @mbggenerated
     */
    public void setLevel2Name(String level2Name) {
        this.level2Name = level2Name == null ? null : level2Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_project_detail.level_3_name
     *
     * @return the value of cost_project_detail.level_3_name
     *
     * @mbggenerated
     */
    public String getLevel3Name() {
        return level3Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_project_detail.level_3_name
     *
     * @param level3Name the value for cost_project_detail.level_3_name
     *
     * @mbggenerated
     */
    public void setLevel3Name(String level3Name) {
        this.level3Name = level3Name == null ? null : level3Name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_project_detail.unit
     *
     * @return the value of cost_project_detail.unit
     *
     * @mbggenerated
     */
    public String getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_project_detail.unit
     *
     * @param unit the value for cost_project_detail.unit
     *
     * @mbggenerated
     */
    public void setUnit(String unit) {
        this.unit = unit == null ? null : unit.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_project_detail.supply_unit_cost
     *
     * @return the value of cost_project_detail.supply_unit_cost
     *
     * @mbggenerated
     */
    public Long getSupplyUnitCost() {
        return supplyUnitCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_project_detail.supply_unit_cost
     *
     * @param supplyUnitCost the value for cost_project_detail.supply_unit_cost
     *
     * @mbggenerated
     */
    public void setSupplyUnitCost(Long supplyUnitCost) {
        this.supplyUnitCost = supplyUnitCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_project_detail.install_unit_cost
     *
     * @return the value of cost_project_detail.install_unit_cost
     *
     * @mbggenerated
     */
    public Long getInstallUnitCost() {
        return installUnitCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_project_detail.install_unit_cost
     *
     * @param installUnitCost the value for cost_project_detail.install_unit_cost
     *
     * @mbggenerated
     */
    public void setInstallUnitCost(Long installUnitCost) {
        this.installUnitCost = installUnitCost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_project_detail.cost_project_id
     *
     * @return the value of cost_project_detail.cost_project_id
     *
     * @mbggenerated
     */
    public Integer getCostProjectId() {
        return costProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_project_detail.cost_project_id
     *
     * @param costProjectId the value for cost_project_detail.cost_project_id
     *
     * @mbggenerated
     */
    public void setCostProjectId(Integer costProjectId) {
        this.costProjectId = costProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cost_project_detail.level_4_name
     *
     * @return the value of cost_project_detail.level_4_name
     *
     * @mbggenerated
     */
    public String getLevel4Name() {
        return level4Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cost_project_detail.level_4_name
     *
     * @param level4Name the value for cost_project_detail.level_4_name
     *
     * @mbggenerated
     */
    public void setLevel4Name(String level4Name) {
        this.level4Name = level4Name == null ? null : level4Name.trim();
    }
}