package leo.wan.model;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table question_item
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class QuestionItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_item.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_item.attribute
     *
     * @mbggenerated
     */
    private String attribute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_item.sub_arrtibute
     *
     * @mbggenerated
     */
    private String subArrtibute;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_item.question_type
     *
     * @mbggenerated
     */
    private String questionType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_item.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question_item.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_item.id
     *
     * @return the value of question_item.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_item.id
     *
     * @param id the value for question_item.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_item.attribute
     *
     * @return the value of question_item.attribute
     *
     * @mbggenerated
     */
    public String getAttribute() {
        return attribute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_item.attribute
     *
     * @param attribute the value for question_item.attribute
     *
     * @mbggenerated
     */
    public void setAttribute(String attribute) {
        this.attribute = attribute == null ? null : attribute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_item.sub_arrtibute
     *
     * @return the value of question_item.sub_arrtibute
     *
     * @mbggenerated
     */
    public String getSubArrtibute() {
        return subArrtibute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_item.sub_arrtibute
     *
     * @param subArrtibute the value for question_item.sub_arrtibute
     *
     * @mbggenerated
     */
    public void setSubArrtibute(String subArrtibute) {
        this.subArrtibute = subArrtibute == null ? null : subArrtibute.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_item.question_type
     *
     * @return the value of question_item.question_type
     *
     * @mbggenerated
     */
    public String getQuestionType() {
        return questionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_item.question_type
     *
     * @param questionType the value for question_item.question_type
     *
     * @mbggenerated
     */
    public void setQuestionType(String questionType) {
        this.questionType = questionType == null ? null : questionType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_item.update_time
     *
     * @return the value of question_item.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_item.update_time
     *
     * @param updateTime the value for question_item.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question_item.create_time
     *
     * @return the value of question_item.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question_item.create_time
     *
     * @param createTime the value for question_item.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}