package leo.wan.model;

import java.math.BigDecimal;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table role
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class Role {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.role_name
     *
     * @mbggenerated
     */
    private String roleName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.roleLevel
     *
     * @mbggenerated
     */
    private String rolelevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.isUsed
     *
     * @mbggenerated
     */
    private Byte isused;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.amount
     *
     * @mbggenerated
     */
    private Double amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.int_Total
     *
     * @mbggenerated
     */
    private Integer intTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column role.decemil_Toal
     *
     * @mbggenerated
     */
    private BigDecimal decemilToal;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    public Role(Integer id, String roleName, String rolelevel, Byte isused, Double amount, Integer intTotal, BigDecimal decemilToal) {
        this.id = id;
        this.roleName = roleName;
        this.rolelevel = rolelevel;
        this.isused = isused;
        this.amount = amount;
        this.intTotal = intTotal;
        this.decemilToal = decemilToal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role
     *
     * @mbggenerated
     */
    public Role() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.id
     *
     * @return the value of role.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.id
     *
     * @param id the value for role.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.role_name
     *
     * @return the value of role.role_name
     *
     * @mbggenerated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.role_name
     *
     * @param roleName the value for role.role_name
     *
     * @mbggenerated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.roleLevel
     *
     * @return the value of role.roleLevel
     *
     * @mbggenerated
     */
    public String getRolelevel() {
        return rolelevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.roleLevel
     *
     * @param rolelevel the value for role.roleLevel
     *
     * @mbggenerated
     */
    public void setRolelevel(String rolelevel) {
        this.rolelevel = rolelevel == null ? null : rolelevel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.isUsed
     *
     * @return the value of role.isUsed
     *
     * @mbggenerated
     */
    public Byte getIsused() {
        return isused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.isUsed
     *
     * @param isused the value for role.isUsed
     *
     * @mbggenerated
     */
    public void setIsused(Byte isused) {
        this.isused = isused;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.amount
     *
     * @return the value of role.amount
     *
     * @mbggenerated
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.amount
     *
     * @param amount the value for role.amount
     *
     * @mbggenerated
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.int_Total
     *
     * @return the value of role.int_Total
     *
     * @mbggenerated
     */
    public Integer getIntTotal() {
        return intTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.int_Total
     *
     * @param intTotal the value for role.int_Total
     *
     * @mbggenerated
     */
    public void setIntTotal(Integer intTotal) {
        this.intTotal = intTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column role.decemil_Toal
     *
     * @return the value of role.decemil_Toal
     *
     * @mbggenerated
     */
    public BigDecimal getDecemilToal() {
        return decemilToal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column role.decemil_Toal
     *
     * @param decemilToal the value for role.decemil_Toal
     *
     * @mbggenerated
     */
    public void setDecemilToal(BigDecimal decemilToal) {
        this.decemilToal = decemilToal;
    }

}