package leo.wan.dao;

import java.util.List;
import leo.wan.model.CostProjectDetail;
import leo.wan.model.CostProjectDetailExample;
import org.apache.ibatis.annotations.Param;

public interface CostProjectDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    int countByExample(CostProjectDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    int deleteByExample(CostProjectDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    int insert(CostProjectDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    int insertSelective(CostProjectDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    List<CostProjectDetail> selectByExample(CostProjectDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    CostProjectDetail selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") CostProjectDetail record, @Param("example") CostProjectDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") CostProjectDetail record, @Param("example") CostProjectDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(CostProjectDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cost_project_detail
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(CostProjectDetail record);
}