package leo.wan.dao;

import java.util.List;
import leo.wan.model.QuestionItem;
import leo.wan.model.QuestionItemExample;
import org.apache.ibatis.annotations.Param;

public interface QuestionItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_item
     *
     * @mbggenerated
     */
    int countByExample(QuestionItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_item
     *
     * @mbggenerated
     */
    int deleteByExample(QuestionItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_item
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_item
     *
     * @mbggenerated
     */
    int insert(QuestionItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_item
     *
     * @mbggenerated
     */
    int insertSelective(QuestionItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_item
     *
     * @mbggenerated
     */
    List<QuestionItem> selectByExample(QuestionItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_item
     *
     * @mbggenerated
     */
    QuestionItem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_item
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") QuestionItem record, @Param("example") QuestionItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_item
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") QuestionItem record, @Param("example") QuestionItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(QuestionItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_item
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(QuestionItem record);
}